#!/bin/sh
BASEDIR=$(dirname $0)
TESTDIR=$BASEDIR/../../test
FIXDIR=$BASEDIR/../../test/fixtures
TEMPDIR=$BASEDIR/../../test/temp

if [ ! -d "$TEMPDIR" ]; then
	mkdir $TEMPDIR
fi

for f in $FIXDIR/*
do
  #echo "$f"
  uglifyjs $f > $TEMPDIR/$(basename $f)
  rm $f
  mv $TEMPDIR/$(basename $f) $f
done  
