#!/bin/sh
BASEDIR=$(dirname $0)
TESTDIR=$BASEDIR/../../test
FIXDIR=$BASEDIR/../../test/fixtures
MINDIR=$BASEDIR/../../test/min

if [ ! -d "$MINDIR" ]; then
	mkdir $MINDIR
fi

for f in $FIXDIR/*
do
  #echo "$f"
  uglifyjs $f > $MINDIR/$(basename $f)
  rm $f
  mv $MINDIR/$(basename $f) $f
done  
